/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ongc.liferay.mediatags.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Tags service. Represents a row in the &quot;ongc_Tags&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ongc.liferay.mediatags.model.impl.TagsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ongc.liferay.mediatags.model.impl.TagsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Tags
 * @generated
 */
@ProviderType
public interface TagsModel
	extends BaseModel<Tags>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tags model instance should use the {@link Tags} interface instead.
	 */

	/**
	 * Returns the primary key of this tags.
	 *
	 * @return the primary key of this tags
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tags.
	 *
	 * @param primaryKey the primary key of this tags
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this tags.
	 *
	 * @return the uuid of this tags
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this tags.
	 *
	 * @param uuid the uuid of this tags
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the tag ID of this tags.
	 *
	 * @return the tag ID of this tags
	 */
	public long getTagId();

	/**
	 * Sets the tag ID of this tags.
	 *
	 * @param tagId the tag ID of this tags
	 */
	public void setTagId(long tagId);

	/**
	 * Returns the group ID of this tags.
	 *
	 * @return the group ID of this tags
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this tags.
	 *
	 * @param groupId the group ID of this tags
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this tags.
	 *
	 * @return the company ID of this tags
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this tags.
	 *
	 * @param companyId the company ID of this tags
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this tags.
	 *
	 * @return the user ID of this tags
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this tags.
	 *
	 * @param userId the user ID of this tags
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this tags.
	 *
	 * @return the user uuid of this tags
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this tags.
	 *
	 * @param userUuid the user uuid of this tags
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this tags.
	 *
	 * @return the user name of this tags
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this tags.
	 *
	 * @param userName the user name of this tags
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this tags.
	 *
	 * @return the create date of this tags
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this tags.
	 *
	 * @param createDate the create date of this tags
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this tags.
	 *
	 * @return the modified date of this tags
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this tags.
	 *
	 * @param modifiedDate the modified date of this tags
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the tag name of this tags.
	 *
	 * @return the tag name of this tags
	 */
	@AutoEscape
	public String getTagName();

	/**
	 * Sets the tag name of this tags.
	 *
	 * @param tagName the tag name of this tags
	 */
	public void setTagName(String tagName);

	@Override
	public Tags cloneWithOriginalValues();

}